#!/bin/sh

set -e

case "$1" in
    configure|reconfigure)
        case "`lsb_release -cs`" in
            wheezy)
                pip install -q -U -i https://pypi.python.org/simple/ pip==9.0.3 2>/dev/null
                hash -r
                pip install -q -i https://pypi.python.org/simple/ -r /usr/share/monit-docker/requirements.txt 2>/dev/null
                ;;
            jessie)
                pip install -q -U pip
                hash -r
                pip install -q -r /usr/share/monit-docker/requirements.txt
                ;;
            *)
                pip install -q -r /usr/share/monit-docker/requirements.txt
            ;;
        esac
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
